extern long double x;
extern long double y;
extern double theta;
extern bool L1_pressing;
extern bool clamped;
extern bool R1_pressing;
extern bool doinked;
extern bool intakeToFrogAuton;
extern bool intakeSort;
extern bool intakeRev;
extern bool pre_match;
extern bool pre_driver;